feat(run-lighthouse-tests): init [ED-325]
elementor/elementor-editor-github-actions pull request #17
Opened 2024-08-06 09:36 UTC by Nevoss

2024-08-07 07:59 UTC, StyleShit requested changes

2024-08-07 07:59 UTC, StyleShit commented on actions/outputs.ts
> +	);
🔥

2024-08-07 07:59 UTC, StyleShit commented on actions/run-lighthouse-tests/action.yml
> +        description: A list of URLs to test, separated by new lines (e.g. `moshe:http://localhost:8889/moshe \n haim:http://localhost:8889/haim`)
```suggestion
        description: A map of URLs to test, with aliases as keys, separated by new lines (e.g. `moshe:http://localhost:8889/moshe \n haim:http://localhost:8889/haim`)
```

2024-08-07 07:59 UTC, StyleShit commented on actions/run-lighthouse-tests/action.yml
> +        required: false
why is it optional?

2024-08-07 07:59 UTC, StyleShit commented on actions/run-lighthouse-tests/main.ts
> +				onlyCategories: [] as string[], // Will be filled in later.
```suggestion
				onlyCategories: [] as Array<typeof AVAILABLE_CATEGORIES[number]>, // Will be filled in later.
```

maybe?

2024-08-07 07:59 UTC, StyleShit commented on actions/run-lighthouse-tests/main.ts
> +			setOutput(`reports-path`, OUTPUT_DIR);
```suggestion
			setOutput('reports-path', OUTPUT_DIR);
```

2024-08-07 07:59 UTC, StyleShit commented on actions/run-lighthouse-tests/main.ts
> +					await exec.exec('rm', ['-rf', './.lighthouseci']);
```suggestion
					await exec.exec('rm', ['-rf', OUTPUT_DIR, './.lighthouseci']);
```

2024-08-08 04:53 UTC, Nevoss commented on actions/run-lighthouse-tests/action.yml
> +        description: A list of URLs to test, separated by new lines (e.g. `moshe:http://localhost:8889/moshe \n haim:http://localhost:8889/haim`)
Done

2024-08-08 04:53 UTC, Nevoss commented on actions/run-lighthouse-tests/action.yml
> +        required: false
Done

2024-08-08 04:54 UTC, Nevoss commented on actions/run-lighthouse-tests/main.ts
> +				onlyCategories: [] as string[], // Will be filled in later.
Done

2024-08-08 04:55 UTC, Nevoss commented on actions/run-lighthouse-tests/main.ts
> +			setOutput(`reports-path`, OUTPUT_DIR);
Done

2024-08-08 04:56 UTC, Nevoss commented on actions/run-lighthouse-tests/main.ts
> +					await exec.exec('rm', ['-rf', './.lighthouseci']);
Done

2024-08-08 05:11 UTC, StyleShit approved these changes

2024-08-08 05:12 UTC, merged